version: '3.7'

services:
    web:
        container_name: web
        hostname: web
        build:
            context: ./web
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - db
        volumes:
            - ./web/html:/var/www/html
        ports:
            - 80:80
        networks:
            - db-network
            - web-network

    db:
        container_name: db
        hostname: db
        image: mariadb:10.7.8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: R00tP4ssw0rd #Config your own root password.
            MYSQL_USER: hw_user #Config your own user. This needs to be the same like html/config/config.php $user.
            MYSQL_PASSWORD: hw_password #Config your own password. This needs to be the same like html/config/config.php $pass.
            MYSQL_DATABASE: homeweather
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - db-network

    pma:
        container_name: pma
        hostname: pma
        image: phpmyadmin:5.2.1
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        networks:
            - db-network
            - web-network

volumes:
    db-data:
        name: homeweather-db-data

networks:
    web-network:
        name: homeweather-web-network
        driver: bridge

    db-network:
        name: homeweather-db-network
        driver: bridge
